#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

picom -CGb & 
setxkbmap -option ctrl:nocaps &
# Set up an icon tray hidpi 1.25
trayer --edge top --align right --SetDockType true --SetPartialStrut true \
 --expand true --width 10 --transparent true --tint 0x5f5f5f --height 37 &

# Set the default X cursor to the usual pointer
xsetroot -cursor_name left_ptr

# Fire up screensaver
xscreensaver -no-splash &# Fire up screensaver

feh --bg-scale ~/Sources/dotfiles/wallpapers/pinky-astronaut-wallpaper.jpg &
clash &
fcitx5 -d
exec xmonad
