# export WLR_NO_HARDWARE_CURSORS=1
# export MOZ_ENABLE_WAYLAND=1
# export KITTY_ENABLE_WAYLAND=1
# export GTK_IM_MODULE=fcitx
# export XMODIFIERS=@im=fcitx
[ "$(tty)" = "/dev/tty1" ] && exec Hyprland
