## rust
source "$HOME/.cargo/env"

## go
export GOPATH="$HOME/WorkSpace/golang"
export PATH="$PATH:$GOPATH/bin"
export GO111MODULE=on
export GOPROXY=https://goproxy.io

## python
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv virtualenv-init -)"

## yarn tools
export PATH=$HOME/.yarn/bin:$PATH

##Bat
export BAT_THEME="TwoDark"
