export https_proxy=http://127.0.0.1:7890
export http_proxy=http://127.0.0.1:7890 
export all_proxy=socks5://127.0.0.1:7891

alias ipi="curl cip.cc"
alias ls="exa --icons"
alias ll="exa -l --icons"
alias la="exa -la --icons"
alias tree="exa -T --icons"
alias vi="nvim"
alias vim="nvim"
alias cat="bat"
alias reload="source ~/.zshrc"
alias demacs="emacs --dump-file='/Users/neo/.config/emacs/emacs.pdmp'"

## starship
eval "$(starship init zsh)"

## zoxide
eval "$(zoxide init zsh)"

### Added by Zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
	print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
	command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
	command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
		print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
		print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
	zinit-zsh/z-a-rust \
	zinit-zsh/z-a-as-monitor \
	zinit-zsh/z-a-patch-dl \
	zinit-zsh/z-a-bin-gem-node

# OMZ plugins
zinit snippet OMZ::lib/history.zsh
zinit ice wait lucid 
zinit snippet OMZ::lib/completion.zsh

zinit ice wait lucid atload"unalias grv"
zinit snippet OMZ::plugins/git/git.plugin.zsh

# Plugins
zinit ice depth=1 wait lucid atinit"ZINIT[COMPINIT_OPTS]=-C; zpcompinit; zpcdreplay"
zinit light zdharma/fast-syntax-highlighting

zinit ice depth=1 wait lucid compile"{src/*.zsh,src/strategies/*.zsh}" atload"_zsh_autosuggest_start"
zinit light zsh-users/zsh-autosuggestions

zinit ice depth=1 wait"2" lucid
zinit light hlissner/zsh-autopair

zinit ice depth=1 wait"2" lucid
zinit light MichaelAquilina/zsh-you-should-use
### End of Zinit's installer chunk
